const PROJECT_CONTEXT_BLOCK_TYPE = {
  PROMPT: 'prompt'
};

const PROJECT_CONTEXT_PLACEHOLDERS = {
  PROJECT_CONTEXT: '{PROJECT_CONTEXT}'
};

export default PROJECT_CONTEXT_BLOCK_TYPE;
export {PROJECT_CONTEXT_PLACEHOLDERS};
